create table FILM
(
    FILM_ID             NUMBER not null,
    FILM_TITRE          VARCHAR2(50),
    FILM_LANGUE         VARCHAR2(50),
    FILM_TEMPS          VARCHAR2(50),
    FILM_TYPE           VARCHAR2(50),
    FILM_DATE_DE_SORTIE DATE,
    CAISSIER_ID         NUMBER not null,
    REALISATEUR         VARCHAR2(20),
    PAYS_DE_PRODUCTION  VARCHAR2(20)
)
/

INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (14486, 'SIA LE RÊVE DU PYTHON', 'Français', '90', 'drame', TO_DATE('2002-06-02 12:13:26', 'YYYY-MM-DD HH24:MI:SS'), 929, 'Dani Kouyaté', 'BURKINA FASO');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (26548, 'ALI ZAOUA PRINCE DE LA RUE', 'Français', '90', 'drame', TO_DATE('2001-03-21 12:34:30', 'YYYY-MM-DD HH24:MI:SS'), 927, '	Nabil Ayouch', 'MAROC');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (36545, 'LE FAUTEUIL', 'Français', '92', 'drame', TO_DATE('2009-03-07 12:52:28', 'YYYY-MM-DD HH24:MI:SS'), 930, 'Missa Hébié', 'BURKINA FASO');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (43540, 'EN ATTENDANT LE BONHEUR', 'Français', '90', 'drame', TO_DATE('2003-01-15 12:54:44', 'YYYY-MM-DD HH24:MI:SS'), 925, 'Abderrahmane Sissako', 'MAURITANIE');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (58525, 'UN HOMME QUI CRIE', 'Français', '95', 'guerre', TO_DATE('2010-09-29 13:16:44', 'YYYY-MM-DD HH24:MI:SS'), 926, 'Mahamat-Saleh Haroun', 'TCHAD');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (65653, 'NOTRE ÉTRANGÈRE', 'Français', '82', '		ComédieComédie', TO_DATE('2001-02-02 13:19:26', 'YYYY-MM-DD HH24:MI:SS'), 924, 'Sarah Bouyain', 'BURKINA FASO');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (75266, 'LE MEC IDÉAL', 'Français', '110', 'Comédie', TO_DATE('2011-03-09 13:21:49', 'YYYY-MM-DD HH24:MI:SS'), 923, 'Owell Brown', 'COTE D`IVOIRE');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (88552, 'TEZA', 'Français', '140', 'drame', TO_DATE('2008-04-23 13:25:39', 'YYYY-MM-DD HH24:MI:SS'), 920, 'Haile Gerima', 'ETHIOPIE');
INSERT INTO SMI1002_011.FILM (FILM_ID, FILM_TITRE, FILM_LANGUE, FILM_TEMPS, FILM_TYPE, FILM_DATE_DE_SORTIE, CAISSIER_ID, REALISATEUR, PAYS_DE_PRODUCTION) VALUES (95236, 'LINGUI, LES LIENS SACRÉS', 'Français', '95', 'drame', TO_DATE('2021-12-08 13:38:36', 'YYYY-MM-DD HH24:MI:SS'), 919, 'Mahamat-Saleh Haroun', 'TCHAD');
